// Code generated by mk_composite_index.go, DO NOT EDIT.
package types

import (
	"fmt"

	"github.com/tdakkota/win32metadata/md"
)

var _ fmt.Stringer

// TypeDefOrRef represents composite index one of
//
// 	TypeDef
// 	TypeRef
// 	TypeSpec
//
// table.
type TypeDefOrRef uint32

// Tag returns TypeDefOrRef tag.
// Tag table:
//
// 	TypeDef = 0
// 	TypeRef = 1
// 	TypeSpec = 2
//
func (t TypeDefOrRef) Tag() uint32 {
	return uint32(t & ((1 << 2) - 1))
}

// Table returns associated TableType using tag.
func (t TypeDefOrRef) Table() (md.TableType, bool) {
	switch t.Tag() {
	case 0:
		return md.TypeDef, true
	case 1:
		return md.TypeRef, true
	case 2:
		return md.TypeSpec, true
	default:
		return 0, false
	}
}

// Row creates new Row using given Context and this index.
func (t TypeDefOrRef) Row(c *Context) (Row, bool) {
	table, ok := t.Table()
	if !ok {
		var zero Row
		return zero, false
	}

	return c.Table(table).Row(t.TableIndex()), true
}

// TableIndex returns TypeDefOrRef index.
func (t TypeDefOrRef) TableIndex() uint32 {
	return uint32((t >> 2) - 1)
}

// String implements fmt.Stringer method.
func (t TypeDefOrRef) String() string {
	switch t.Tag() {
	case 0:
		return fmt.Sprintf("TypeDef(%d)", t.TableIndex())
	case 1:
		return fmt.Sprintf("TypeRef(%d)", t.TableIndex())
	case 2:
		return fmt.Sprintf("TypeSpec(%d)", t.TableIndex())
	default:
		return "unknown"
	}
}

// HasConstant represents composite index one of
//
// 	Field
// 	Param
// 	Property
//
// table.
type HasConstant uint32

// Tag returns HasConstant tag.
// Tag table:
//
// 	Field = 0
// 	Param = 1
// 	Property = 2
//
func (t HasConstant) Tag() uint32 {
	return uint32(t & ((1 << 2) - 1))
}

// Table returns associated TableType using tag.
func (t HasConstant) Table() (md.TableType, bool) {
	switch t.Tag() {
	case 0:
		return md.Field, true
	case 1:
		return md.Param, true
	case 2:
		return md.Property, true
	default:
		return 0, false
	}
}

// Row creates new Row using given Context and this index.
func (t HasConstant) Row(c *Context) (Row, bool) {
	table, ok := t.Table()
	if !ok {
		var zero Row
		return zero, false
	}

	return c.Table(table).Row(t.TableIndex()), true
}

// TableIndex returns HasConstant index.
func (t HasConstant) TableIndex() uint32 {
	return uint32((t >> 2) - 1)
}

// String implements fmt.Stringer method.
func (t HasConstant) String() string {
	switch t.Tag() {
	case 0:
		return fmt.Sprintf("Field(%d)", t.TableIndex())
	case 1:
		return fmt.Sprintf("Param(%d)", t.TableIndex())
	case 2:
		return fmt.Sprintf("Property(%d)", t.TableIndex())
	default:
		return "unknown"
	}
}

// HasCustomAttribute represents composite index one of
//
// 	MethodDef
// 	Field
// 	TypeRef
// 	TypeDef
// 	Param
// 	InterfaceImpl
// 	MemberRef
// 	Module
// 	Permission
// 	Property
// 	Event
// 	StandAloneSig
// 	ModuleRef
// 	TypeSpec
// 	Assembly
// 	AssemblyRef
// 	File
// 	ExportedType
// 	ManifestResource
// 	GenericParam
// 	GenericParamConstraint
// 	MethodSpec
//
// table.
type HasCustomAttribute uint32

// Tag returns HasCustomAttribute tag.
// Tag table:
//
// 	MethodDef = 0
// 	Field = 1
// 	TypeRef = 2
// 	TypeDef = 3
// 	Param = 4
// 	InterfaceImpl = 5
// 	MemberRef = 6
// 	Module = 7
// 	Permission = 8
// 	Property = 9
// 	Event = 10
// 	StandAloneSig = 11
// 	ModuleRef = 12
// 	TypeSpec = 13
// 	Assembly = 14
// 	AssemblyRef = 15
// 	File = 16
// 	ExportedType = 17
// 	ManifestResource = 18
// 	GenericParam = 19
// 	GenericParamConstraint = 20
// 	MethodSpec = 21
//
func (t HasCustomAttribute) Tag() uint32 {
	return uint32(t & ((1 << 5) - 1))
}

// Table returns associated TableType using tag.
func (t HasCustomAttribute) Table() (md.TableType, bool) {
	switch t.Tag() {
	case 0:
		return md.MethodDef, true
	case 1:
		return md.Field, true
	case 2:
		return md.TypeRef, true
	case 3:
		return md.TypeDef, true
	case 4:
		return md.Param, true
	case 5:
		return md.InterfaceImpl, true
	case 6:
		return md.MemberRef, true
	case 7:
		return md.Module, true
	// Skip 8 "Permission", there is not such table
	case 9:
		return md.Property, true
	case 10:
		return md.Event, true
	case 11:
		return md.StandAloneSig, true
	case 12:
		return md.ModuleRef, true
	case 13:
		return md.TypeSpec, true
	case 14:
		return md.Assembly, true
	case 15:
		return md.AssemblyRef, true
	case 16:
		return md.File, true
	case 17:
		return md.ExportedType, true
	case 18:
		return md.ManifestResource, true
	case 19:
		return md.GenericParam, true
	case 20:
		return md.GenericParamConstraint, true
	case 21:
		return md.MethodSpec, true
	default:
		return 0, false
	}
}

// Row creates new Row using given Context and this index.
func (t HasCustomAttribute) Row(c *Context) (Row, bool) {
	table, ok := t.Table()
	if !ok {
		var zero Row
		return zero, false
	}

	return c.Table(table).Row(t.TableIndex()), true
}

// TableIndex returns HasCustomAttribute index.
func (t HasCustomAttribute) TableIndex() uint32 {
	return uint32((t >> 5) - 1)
}

// String implements fmt.Stringer method.
func (t HasCustomAttribute) String() string {
	switch t.Tag() {
	case 0:
		return fmt.Sprintf("MethodDef(%d)", t.TableIndex())
	case 1:
		return fmt.Sprintf("Field(%d)", t.TableIndex())
	case 2:
		return fmt.Sprintf("TypeRef(%d)", t.TableIndex())
	case 3:
		return fmt.Sprintf("TypeDef(%d)", t.TableIndex())
	case 4:
		return fmt.Sprintf("Param(%d)", t.TableIndex())
	case 5:
		return fmt.Sprintf("InterfaceImpl(%d)", t.TableIndex())
	case 6:
		return fmt.Sprintf("MemberRef(%d)", t.TableIndex())
	case 7:
		return fmt.Sprintf("Module(%d)", t.TableIndex())
	case 8:
		return fmt.Sprintf("Permission(%d)", t.TableIndex())
	case 9:
		return fmt.Sprintf("Property(%d)", t.TableIndex())
	case 10:
		return fmt.Sprintf("Event(%d)", t.TableIndex())
	case 11:
		return fmt.Sprintf("StandAloneSig(%d)", t.TableIndex())
	case 12:
		return fmt.Sprintf("ModuleRef(%d)", t.TableIndex())
	case 13:
		return fmt.Sprintf("TypeSpec(%d)", t.TableIndex())
	case 14:
		return fmt.Sprintf("Assembly(%d)", t.TableIndex())
	case 15:
		return fmt.Sprintf("AssemblyRef(%d)", t.TableIndex())
	case 16:
		return fmt.Sprintf("File(%d)", t.TableIndex())
	case 17:
		return fmt.Sprintf("ExportedType(%d)", t.TableIndex())
	case 18:
		return fmt.Sprintf("ManifestResource(%d)", t.TableIndex())
	case 19:
		return fmt.Sprintf("GenericParam(%d)", t.TableIndex())
	case 20:
		return fmt.Sprintf("GenericParamConstraint(%d)", t.TableIndex())
	case 21:
		return fmt.Sprintf("MethodSpec(%d)", t.TableIndex())
	default:
		return "unknown"
	}
}

// HasFieldMarshall represents composite index one of
//
// 	Field
// 	Param
//
// table.
type HasFieldMarshall uint32

// Tag returns HasFieldMarshall tag.
// Tag table:
//
// 	Field = 0
// 	Param = 1
//
func (t HasFieldMarshall) Tag() uint32 {
	return uint32(t & ((1 << 1) - 1))
}

// Table returns associated TableType using tag.
func (t HasFieldMarshall) Table() (md.TableType, bool) {
	switch t.Tag() {
	case 0:
		return md.Field, true
	case 1:
		return md.Param, true
	default:
		return 0, false
	}
}

// Row creates new Row using given Context and this index.
func (t HasFieldMarshall) Row(c *Context) (Row, bool) {
	table, ok := t.Table()
	if !ok {
		var zero Row
		return zero, false
	}

	return c.Table(table).Row(t.TableIndex()), true
}

// TableIndex returns HasFieldMarshall index.
func (t HasFieldMarshall) TableIndex() uint32 {
	return uint32((t >> 1) - 1)
}

// String implements fmt.Stringer method.
func (t HasFieldMarshall) String() string {
	switch t.Tag() {
	case 0:
		return fmt.Sprintf("Field(%d)", t.TableIndex())
	case 1:
		return fmt.Sprintf("Param(%d)", t.TableIndex())
	default:
		return "unknown"
	}
}

// HasDeclSecurity represents composite index one of
//
// 	TypeDef
// 	MethodDef
// 	Assembly
//
// table.
type HasDeclSecurity uint32

// Tag returns HasDeclSecurity tag.
// Tag table:
//
// 	TypeDef = 0
// 	MethodDef = 1
// 	Assembly = 2
//
func (t HasDeclSecurity) Tag() uint32 {
	return uint32(t & ((1 << 2) - 1))
}

// Table returns associated TableType using tag.
func (t HasDeclSecurity) Table() (md.TableType, bool) {
	switch t.Tag() {
	case 0:
		return md.TypeDef, true
	case 1:
		return md.MethodDef, true
	case 2:
		return md.Assembly, true
	default:
		return 0, false
	}
}

// Row creates new Row using given Context and this index.
func (t HasDeclSecurity) Row(c *Context) (Row, bool) {
	table, ok := t.Table()
	if !ok {
		var zero Row
		return zero, false
	}

	return c.Table(table).Row(t.TableIndex()), true
}

// TableIndex returns HasDeclSecurity index.
func (t HasDeclSecurity) TableIndex() uint32 {
	return uint32((t >> 2) - 1)
}

// String implements fmt.Stringer method.
func (t HasDeclSecurity) String() string {
	switch t.Tag() {
	case 0:
		return fmt.Sprintf("TypeDef(%d)", t.TableIndex())
	case 1:
		return fmt.Sprintf("MethodDef(%d)", t.TableIndex())
	case 2:
		return fmt.Sprintf("Assembly(%d)", t.TableIndex())
	default:
		return "unknown"
	}
}

// MemberRefParent represents composite index one of
//
// 	TypeDef
// 	TypeRef
// 	ModuleRef
// 	MethodDef
// 	TypeSpec
//
// table.
type MemberRefParent uint32

// Tag returns MemberRefParent tag.
// Tag table:
//
// 	TypeDef = 0
// 	TypeRef = 1
// 	ModuleRef = 2
// 	MethodDef = 3
// 	TypeSpec = 4
//
func (t MemberRefParent) Tag() uint32 {
	return uint32(t & ((1 << 3) - 1))
}

// Table returns associated TableType using tag.
func (t MemberRefParent) Table() (md.TableType, bool) {
	switch t.Tag() {
	case 0:
		return md.TypeDef, true
	case 1:
		return md.TypeRef, true
	case 2:
		return md.ModuleRef, true
	case 3:
		return md.MethodDef, true
	case 4:
		return md.TypeSpec, true
	default:
		return 0, false
	}
}

// Row creates new Row using given Context and this index.
func (t MemberRefParent) Row(c *Context) (Row, bool) {
	table, ok := t.Table()
	if !ok {
		var zero Row
		return zero, false
	}

	return c.Table(table).Row(t.TableIndex()), true
}

// TableIndex returns MemberRefParent index.
func (t MemberRefParent) TableIndex() uint32 {
	return uint32((t >> 3) - 1)
}

// String implements fmt.Stringer method.
func (t MemberRefParent) String() string {
	switch t.Tag() {
	case 0:
		return fmt.Sprintf("TypeDef(%d)", t.TableIndex())
	case 1:
		return fmt.Sprintf("TypeRef(%d)", t.TableIndex())
	case 2:
		return fmt.Sprintf("ModuleRef(%d)", t.TableIndex())
	case 3:
		return fmt.Sprintf("MethodDef(%d)", t.TableIndex())
	case 4:
		return fmt.Sprintf("TypeSpec(%d)", t.TableIndex())
	default:
		return "unknown"
	}
}

// HasSemantics represents composite index one of
//
// 	Event
// 	Property
//
// table.
type HasSemantics uint32

// Tag returns HasSemantics tag.
// Tag table:
//
// 	Event = 0
// 	Property = 1
//
func (t HasSemantics) Tag() uint32 {
	return uint32(t & ((1 << 1) - 1))
}

// Table returns associated TableType using tag.
func (t HasSemantics) Table() (md.TableType, bool) {
	switch t.Tag() {
	case 0:
		return md.Event, true
	case 1:
		return md.Property, true
	default:
		return 0, false
	}
}

// Row creates new Row using given Context and this index.
func (t HasSemantics) Row(c *Context) (Row, bool) {
	table, ok := t.Table()
	if !ok {
		var zero Row
		return zero, false
	}

	return c.Table(table).Row(t.TableIndex()), true
}

// TableIndex returns HasSemantics index.
func (t HasSemantics) TableIndex() uint32 {
	return uint32((t >> 1) - 1)
}

// String implements fmt.Stringer method.
func (t HasSemantics) String() string {
	switch t.Tag() {
	case 0:
		return fmt.Sprintf("Event(%d)", t.TableIndex())
	case 1:
		return fmt.Sprintf("Property(%d)", t.TableIndex())
	default:
		return "unknown"
	}
}

// MethodDefOrRef represents composite index one of
//
// 	MethodDef
// 	MemberRef
//
// table.
type MethodDefOrRef uint32

// Tag returns MethodDefOrRef tag.
// Tag table:
//
// 	MethodDef = 0
// 	MemberRef = 1
//
func (t MethodDefOrRef) Tag() uint32 {
	return uint32(t & ((1 << 1) - 1))
}

// Table returns associated TableType using tag.
func (t MethodDefOrRef) Table() (md.TableType, bool) {
	switch t.Tag() {
	case 0:
		return md.MethodDef, true
	case 1:
		return md.MemberRef, true
	default:
		return 0, false
	}
}

// Row creates new Row using given Context and this index.
func (t MethodDefOrRef) Row(c *Context) (Row, bool) {
	table, ok := t.Table()
	if !ok {
		var zero Row
		return zero, false
	}

	return c.Table(table).Row(t.TableIndex()), true
}

// TableIndex returns MethodDefOrRef index.
func (t MethodDefOrRef) TableIndex() uint32 {
	return uint32((t >> 1) - 1)
}

// String implements fmt.Stringer method.
func (t MethodDefOrRef) String() string {
	switch t.Tag() {
	case 0:
		return fmt.Sprintf("MethodDef(%d)", t.TableIndex())
	case 1:
		return fmt.Sprintf("MemberRef(%d)", t.TableIndex())
	default:
		return "unknown"
	}
}

// MemberForwarded represents composite index one of
//
// 	Field
// 	MethodDef
//
// table.
type MemberForwarded uint32

// Tag returns MemberForwarded tag.
// Tag table:
//
// 	Field = 0
// 	MethodDef = 1
//
func (t MemberForwarded) Tag() uint32 {
	return uint32(t & ((1 << 1) - 1))
}

// Table returns associated TableType using tag.
func (t MemberForwarded) Table() (md.TableType, bool) {
	switch t.Tag() {
	case 0:
		return md.Field, true
	case 1:
		return md.MethodDef, true
	default:
		return 0, false
	}
}

// Row creates new Row using given Context and this index.
func (t MemberForwarded) Row(c *Context) (Row, bool) {
	table, ok := t.Table()
	if !ok {
		var zero Row
		return zero, false
	}

	return c.Table(table).Row(t.TableIndex()), true
}

// TableIndex returns MemberForwarded index.
func (t MemberForwarded) TableIndex() uint32 {
	return uint32((t >> 1) - 1)
}

// String implements fmt.Stringer method.
func (t MemberForwarded) String() string {
	switch t.Tag() {
	case 0:
		return fmt.Sprintf("Field(%d)", t.TableIndex())
	case 1:
		return fmt.Sprintf("MethodDef(%d)", t.TableIndex())
	default:
		return "unknown"
	}
}

// Implementation represents composite index one of
//
// 	File
// 	AssemblyRef
// 	ExportedType
//
// table.
type Implementation uint32

// Tag returns Implementation tag.
// Tag table:
//
// 	File = 0
// 	AssemblyRef = 1
// 	ExportedType = 2
//
func (t Implementation) Tag() uint32 {
	return uint32(t & ((1 << 2) - 1))
}

// Table returns associated TableType using tag.
func (t Implementation) Table() (md.TableType, bool) {
	switch t.Tag() {
	case 0:
		return md.File, true
	case 1:
		return md.AssemblyRef, true
	case 2:
		return md.ExportedType, true
	default:
		return 0, false
	}
}

// Row creates new Row using given Context and this index.
func (t Implementation) Row(c *Context) (Row, bool) {
	table, ok := t.Table()
	if !ok {
		var zero Row
		return zero, false
	}

	return c.Table(table).Row(t.TableIndex()), true
}

// TableIndex returns Implementation index.
func (t Implementation) TableIndex() uint32 {
	return uint32((t >> 2) - 1)
}

// String implements fmt.Stringer method.
func (t Implementation) String() string {
	switch t.Tag() {
	case 0:
		return fmt.Sprintf("File(%d)", t.TableIndex())
	case 1:
		return fmt.Sprintf("AssemblyRef(%d)", t.TableIndex())
	case 2:
		return fmt.Sprintf("ExportedType(%d)", t.TableIndex())
	default:
		return "unknown"
	}
}

// CustomAttributeType represents composite index one of
//
// 	Not used
// 	Not used
// 	MethodDef
// 	MemberRef
// 	Not used
//
// table.
type CustomAttributeType uint32

// Tag returns CustomAttributeType tag.
// Tag table:
//
// 	Not used = 0
// 	Not used = 1
// 	MethodDef = 2
// 	MemberRef = 3
// 	Not used = 4
//
func (t CustomAttributeType) Tag() uint32 {
	return uint32(t & ((1 << 3) - 1))
}

// Table returns associated TableType using tag.
func (t CustomAttributeType) Table() (md.TableType, bool) {
	switch t.Tag() {
	// Skip 0 "Not used", means tag is unused yet
	// Skip 1 "Not used", means tag is unused yet
	case 2:
		return md.MethodDef, true
	case 3:
		return md.MemberRef, true
	// Skip 4 "Not used", means tag is unused yet
	default:
		return 0, false
	}
}

// Row creates new Row using given Context and this index.
func (t CustomAttributeType) Row(c *Context) (Row, bool) {
	table, ok := t.Table()
	if !ok {
		var zero Row
		return zero, false
	}

	return c.Table(table).Row(t.TableIndex()), true
}

// TableIndex returns CustomAttributeType index.
func (t CustomAttributeType) TableIndex() uint32 {
	return uint32((t >> 3) - 1)
}

// String implements fmt.Stringer method.
func (t CustomAttributeType) String() string {
	switch t.Tag() {
	case 0:
		return fmt.Sprintf("Not used(%d)", t.TableIndex())
	case 1:
		return fmt.Sprintf("Not used(%d)", t.TableIndex())
	case 2:
		return fmt.Sprintf("MethodDef(%d)", t.TableIndex())
	case 3:
		return fmt.Sprintf("MemberRef(%d)", t.TableIndex())
	case 4:
		return fmt.Sprintf("Not used(%d)", t.TableIndex())
	default:
		return "unknown"
	}
}

// ResolutionScope represents composite index one of
//
// 	Module
// 	ModuleRef
// 	AssemblyRef
// 	TypeRef
//
// table.
type ResolutionScope uint32

// Tag returns ResolutionScope tag.
// Tag table:
//
// 	Module = 0
// 	ModuleRef = 1
// 	AssemblyRef = 2
// 	TypeRef = 3
//
func (t ResolutionScope) Tag() uint32 {
	return uint32(t & ((1 << 2) - 1))
}

// Table returns associated TableType using tag.
func (t ResolutionScope) Table() (md.TableType, bool) {
	switch t.Tag() {
	case 0:
		return md.Module, true
	case 1:
		return md.ModuleRef, true
	case 2:
		return md.AssemblyRef, true
	case 3:
		return md.TypeRef, true
	default:
		return 0, false
	}
}

// Row creates new Row using given Context and this index.
func (t ResolutionScope) Row(c *Context) (Row, bool) {
	table, ok := t.Table()
	if !ok {
		var zero Row
		return zero, false
	}

	return c.Table(table).Row(t.TableIndex()), true
}

// TableIndex returns ResolutionScope index.
func (t ResolutionScope) TableIndex() uint32 {
	return uint32((t >> 2) - 1)
}

// String implements fmt.Stringer method.
func (t ResolutionScope) String() string {
	switch t.Tag() {
	case 0:
		return fmt.Sprintf("Module(%d)", t.TableIndex())
	case 1:
		return fmt.Sprintf("ModuleRef(%d)", t.TableIndex())
	case 2:
		return fmt.Sprintf("AssemblyRef(%d)", t.TableIndex())
	case 3:
		return fmt.Sprintf("TypeRef(%d)", t.TableIndex())
	default:
		return "unknown"
	}
}

// TypeOrMethodDef represents composite index one of
//
// 	TypeDef
// 	MethodDef
//
// table.
type TypeOrMethodDef uint32

// Tag returns TypeOrMethodDef tag.
// Tag table:
//
// 	TypeDef = 0
// 	MethodDef = 1
//
func (t TypeOrMethodDef) Tag() uint32 {
	return uint32(t & ((1 << 1) - 1))
}

// Table returns associated TableType using tag.
func (t TypeOrMethodDef) Table() (md.TableType, bool) {
	switch t.Tag() {
	case 0:
		return md.TypeDef, true
	case 1:
		return md.MethodDef, true
	default:
		return 0, false
	}
}

// Row creates new Row using given Context and this index.
func (t TypeOrMethodDef) Row(c *Context) (Row, bool) {
	table, ok := t.Table()
	if !ok {
		var zero Row
		return zero, false
	}

	return c.Table(table).Row(t.TableIndex()), true
}

// TableIndex returns TypeOrMethodDef index.
func (t TypeOrMethodDef) TableIndex() uint32 {
	return uint32((t >> 1) - 1)
}

// String implements fmt.Stringer method.
func (t TypeOrMethodDef) String() string {
	switch t.Tag() {
	case 0:
		return fmt.Sprintf("TypeDef(%d)", t.TableIndex())
	case 1:
		return fmt.Sprintf("MethodDef(%d)", t.TableIndex())
	default:
		return "unknown"
	}
}
