// Code generated by "stringer -type=ElementTypeKind"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ELEMENT_TYPE_END-0]
	_ = x[ELEMENT_TYPE_VOID-1]
	_ = x[ELEMENT_TYPE_BOOLEAN-2]
	_ = x[ELEMENT_TYPE_CHAR-3]
	_ = x[ELEMENT_TYPE_I1-4]
	_ = x[ELEMENT_TYPE_U1-5]
	_ = x[ELEMENT_TYPE_I2-6]
	_ = x[ELEMENT_TYPE_U2-7]
	_ = x[ELEMENT_TYPE_I4-8]
	_ = x[ELEMENT_TYPE_U4-9]
	_ = x[ELEMENT_TYPE_I8-10]
	_ = x[ELEMENT_TYPE_U8-11]
	_ = x[ELEMENT_TYPE_R4-12]
	_ = x[ELEMENT_TYPE_R8-13]
	_ = x[ELEMENT_TYPE_STRING-14]
	_ = x[ELEMENT_TYPE_PTR-15]
	_ = x[ELEMENT_TYPE_BYREF-16]
	_ = x[ELEMENT_TYPE_VALUETYPE-17]
	_ = x[ELEMENT_TYPE_CLASS-18]
	_ = x[ELEMENT_TYPE_VAR-19]
	_ = x[ELEMENT_TYPE_ARRAY-20]
	_ = x[ELEMENT_TYPE_GENERICINST-21]
	_ = x[ELEMENT_TYPE_TYPEDBYREF-22]
	_ = x[ELEMENT_TYPE_I-24]
	_ = x[ELEMENT_TYPE_U-25]
	_ = x[ELEMENT_TYPE_FNPTR-27]
	_ = x[ELEMENT_TYPE_OBJECT-28]
	_ = x[ELEMENT_TYPE_SZARRAY-29]
	_ = x[ELEMENT_TYPE_MVAR-30]
	_ = x[ELEMENT_TYPE_CMOD_REQD-31]
	_ = x[ELEMENT_TYPE_CMOD_OPT-32]
	_ = x[ELEMENT_TYPE_INTERNAL-33]
	_ = x[ELEMENT_TYPE_MODIFIER-64]
	_ = x[ELEMENT_TYPE_SENTINEL-65]
	_ = x[ELEMENT_TYPE_PINNED-69]
}

const (
	_ElementTypeKind_name_0 = "ELEMENT_TYPE_ENDELEMENT_TYPE_VOIDELEMENT_TYPE_BOOLEANELEMENT_TYPE_CHARELEMENT_TYPE_I1ELEMENT_TYPE_U1ELEMENT_TYPE_I2ELEMENT_TYPE_U2ELEMENT_TYPE_I4ELEMENT_TYPE_U4ELEMENT_TYPE_I8ELEMENT_TYPE_U8ELEMENT_TYPE_R4ELEMENT_TYPE_R8ELEMENT_TYPE_STRINGELEMENT_TYPE_PTRELEMENT_TYPE_BYREFELEMENT_TYPE_VALUETYPEELEMENT_TYPE_CLASSELEMENT_TYPE_VARELEMENT_TYPE_ARRAYELEMENT_TYPE_GENERICINSTELEMENT_TYPE_TYPEDBYREF"
	_ElementTypeKind_name_1 = "ELEMENT_TYPE_IELEMENT_TYPE_U"
	_ElementTypeKind_name_2 = "ELEMENT_TYPE_FNPTRELEMENT_TYPE_OBJECTELEMENT_TYPE_SZARRAYELEMENT_TYPE_MVARELEMENT_TYPE_CMOD_REQDELEMENT_TYPE_CMOD_OPTELEMENT_TYPE_INTERNAL"
	_ElementTypeKind_name_3 = "ELEMENT_TYPE_MODIFIERELEMENT_TYPE_SENTINEL"
	_ElementTypeKind_name_4 = "ELEMENT_TYPE_PINNED"
)

var (
	_ElementTypeKind_index_0 = [...]uint16{0, 16, 33, 53, 70, 85, 100, 115, 130, 145, 160, 175, 190, 205, 220, 239, 255, 273, 295, 313, 329, 347, 371, 394}
	_ElementTypeKind_index_1 = [...]uint8{0, 14, 28}
	_ElementTypeKind_index_2 = [...]uint8{0, 18, 37, 57, 74, 96, 117, 138}
	_ElementTypeKind_index_3 = [...]uint8{0, 21, 42}
)

func (i ElementTypeKind) String() string {
	switch {
	case i <= 22:
		return _ElementTypeKind_name_0[_ElementTypeKind_index_0[i]:_ElementTypeKind_index_0[i+1]]
	case 24 <= i && i <= 25:
		i -= 24
		return _ElementTypeKind_name_1[_ElementTypeKind_index_1[i]:_ElementTypeKind_index_1[i+1]]
	case 27 <= i && i <= 33:
		i -= 27
		return _ElementTypeKind_name_2[_ElementTypeKind_index_2[i]:_ElementTypeKind_index_2[i+1]]
	case 64 <= i && i <= 65:
		i -= 64
		return _ElementTypeKind_name_3[_ElementTypeKind_index_3[i]:_ElementTypeKind_index_3[i+1]]
	case i == 69:
		return _ElementTypeKind_name_4
	default:
		return "ElementTypeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
