// Code generated by mk_from_row.go, DO NOT EDIT.
package types

import (
	"fmt"

	"github.com/tdakkota/win32metadata/md"
)

// FromRow creates Assembly from given Row.
func (f *Assembly) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field HashAlgId: %w", err)
		}
		f.HashAlgId = AssemblyHashAlgorithm(v)
	}
	{
		v, err := r.Uint64(1)
		if err != nil {
			return fmt.Errorf("decode field Version: %w", err)
		}
		f.Version = uint64(v)
	}
	{
		v, err := r.Uint64(2)
		if err != nil {
			return fmt.Errorf("decode field Flags: %w", err)
		}
		f.Flags = AssemblyFlags(v)
	}
	{
		v, err := r.Blob(3)
		if err != nil {
			return fmt.Errorf("decode field PublicKey: %w", err)
		}
		f.PublicKey = Blob(v)
	}
	{
		v, err := r.String(4)
		if err != nil {
			return fmt.Errorf("decode field Name: %w", err)
		}
		f.Name = string(v)
	}
	{
		v, err := r.String(5)
		if err != nil {
			return fmt.Errorf("decode field Culture: %w", err)
		}
		f.Culture = string(v)
	}
	return nil
}

// FromRow creates AssemblyOS from given Row.
func (f *AssemblyOS) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field OSPlatformID: %w", err)
		}
		f.OSPlatformID = uint32(v)
	}
	{
		v, err := r.Uint64(1)
		if err != nil {
			return fmt.Errorf("decode field OSMajorVersion: %w", err)
		}
		f.OSMajorVersion = uint32(v)
	}
	{
		v, err := r.Uint64(2)
		if err != nil {
			return fmt.Errorf("decode field OSMinorVersion: %w", err)
		}
		f.OSMinorVersion = uint32(v)
	}
	return nil
}

// FromRow creates AssemblyProcessor from given Row.
func (f *AssemblyProcessor) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field Processor: %w", err)
		}
		f.Processor = uint32(v)
	}
	return nil
}

// FromRow creates AssemblyRefOS from given Row.
func (f *AssemblyRefOS) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field OSPlatformID: %w", err)
		}
		f.OSPlatformID = uint32(v)
	}
	{
		v, err := r.Uint64(1)
		if err != nil {
			return fmt.Errorf("decode field OSMajorVersion: %w", err)
		}
		f.OSMajorVersion = uint32(v)
	}
	{
		v, err := r.Uint64(2)
		if err != nil {
			return fmt.Errorf("decode field OSMinorVersion: %w", err)
		}
		f.OSMinorVersion = uint32(v)
	}
	{
		v, err := r.Uint64(3)
		if err != nil {
			return fmt.Errorf("decode field AssemblyRef: %w", err)
		}
		f.AssemblyRef = Index(v)
	}
	return nil
}

// FromRow creates AssemblyRefProcessor from given Row.
func (f *AssemblyRefProcessor) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field Processor: %w", err)
		}
		f.Processor = uint32(v)
	}
	{
		v, err := r.Uint64(1)
		if err != nil {
			return fmt.Errorf("decode field AssemblyRef: %w", err)
		}
		f.AssemblyRef = Index(v)
	}
	return nil
}

// FromRow creates AssemblyRef from given Row.
func (f *AssemblyRef) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field Version: %w", err)
		}
		f.Version = uint64(v)
	}
	{
		v, err := r.Uint64(1)
		if err != nil {
			return fmt.Errorf("decode field Flags: %w", err)
		}
		f.Flags = AssemblyFlags(v)
	}
	{
		v, err := r.Blob(2)
		if err != nil {
			return fmt.Errorf("decode field PublicKeyOrToken: %w", err)
		}
		f.PublicKeyOrToken = Blob(v)
	}
	{
		v, err := r.String(3)
		if err != nil {
			return fmt.Errorf("decode field Name: %w", err)
		}
		f.Name = string(v)
	}
	{
		v, err := r.String(4)
		if err != nil {
			return fmt.Errorf("decode field Culture: %w", err)
		}
		f.Culture = string(v)
	}
	{
		v, err := r.Blob(5)
		if err != nil {
			return fmt.Errorf("decode field HashValue: %w", err)
		}
		f.HashValue = Blob(v)
	}
	return nil
}

// FromRow creates ClassLayout from given Row.
func (f *ClassLayout) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field PackingSize: %w", err)
		}
		f.PackingSize = uint16(v)
	}
	{
		v, err := r.Uint64(1)
		if err != nil {
			return fmt.Errorf("decode field ClassSize: %w", err)
		}
		f.ClassSize = uint32(v)
	}
	{
		v, err := r.Uint64(2)
		if err != nil {
			return fmt.Errorf("decode field Parent: %w", err)
		}
		f.Parent = Index(v)
	}
	return nil
}

// FromRow creates Constant from given Row.
func (f *Constant) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field Type: %w", err)
		}
		f.Type = ElementTypeKind(v)
	}
	{
		v, err := r.Uint64(1)
		if err != nil {
			return fmt.Errorf("decode field Parent: %w", err)
		}
		f.Parent = HasConstant(v)
	}
	{
		v, err := r.Blob(2)
		if err != nil {
			return fmt.Errorf("decode field Value: %w", err)
		}
		f.Value = Blob(v)
	}
	return nil
}

// FromRow creates CustomAttribute from given Row.
func (f *CustomAttribute) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field Parent: %w", err)
		}
		f.Parent = HasCustomAttribute(v)
	}
	{
		v, err := r.Uint64(1)
		if err != nil {
			return fmt.Errorf("decode field Type: %w", err)
		}
		f.Type = CustomAttributeType(v)
	}
	{
		v, err := r.Blob(2)
		if err != nil {
			return fmt.Errorf("decode field Value: %w", err)
		}
		f.Value = Blob(v)
	}
	return nil
}

// FromRow creates DeclSecurity from given Row.
func (f *DeclSecurity) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field Action: %w", err)
		}
		f.Action = uint16(v)
	}
	{
		v, err := r.Uint64(1)
		if err != nil {
			return fmt.Errorf("decode field Parent: %w", err)
		}
		f.Parent = HasDeclSecurity(v)
	}
	{
		v, err := r.Blob(2)
		if err != nil {
			return fmt.Errorf("decode field PermissionSet: %w", err)
		}
		f.PermissionSet = Blob(v)
	}
	return nil
}

// FromRow creates Event from given Row.
func (f *Event) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field EventFlags: %w", err)
		}
		f.EventFlags = EventAttributes(v)
	}
	{
		v, err := r.String(1)
		if err != nil {
			return fmt.Errorf("decode field Name: %w", err)
		}
		f.Name = string(v)
	}
	{
		v, err := r.Uint64(2)
		if err != nil {
			return fmt.Errorf("decode field EventType: %w", err)
		}
		f.EventType = TypeDefOrRef(v)
	}
	return nil
}

// FromRow creates EventMap from given Row.
func (f *EventMap) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field Parent: %w", err)
		}
		f.Parent = Index(v)
	}
	{
		v, err := r.List(1, md.Event)
		if err != nil {
			return fmt.Errorf("decode field EventList: %w", err)
		}
		f.EventList = List(v)
	}
	return nil
}

// FromRow creates ExportedType from given Row.
func (f *ExportedType) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field Flags: %w", err)
		}
		f.Flags = TypeAttributes(v)
	}
	{
		v, err := r.Uint64(1)
		if err != nil {
			return fmt.Errorf("decode field TypeDefId: %w", err)
		}
		f.TypeDefId = uint32(v)
	}
	{
		v, err := r.String(2)
		if err != nil {
			return fmt.Errorf("decode field TypeName: %w", err)
		}
		f.TypeName = string(v)
	}
	{
		v, err := r.String(3)
		if err != nil {
			return fmt.Errorf("decode field TypeNamespace: %w", err)
		}
		f.TypeNamespace = string(v)
	}
	{
		v, err := r.Uint64(4)
		if err != nil {
			return fmt.Errorf("decode field Implementation: %w", err)
		}
		f.Implementation = Implementation(v)
	}
	return nil
}

// FromRow creates Field from given Row.
func (f *Field) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field Flags: %w", err)
		}
		f.Flags = FieldAttributes(v)
	}
	{
		v, err := r.String(1)
		if err != nil {
			return fmt.Errorf("decode field Name: %w", err)
		}
		f.Name = string(v)
	}
	{
		v, err := r.Signature(2)
		if err != nil {
			return fmt.Errorf("decode field Signature: %w", err)
		}
		f.Signature = Signature(v)
	}
	return nil
}

// FromRow creates FieldLayout from given Row.
func (f *FieldLayout) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field Offset: %w", err)
		}
		f.Offset = uint32(v)
	}
	{
		v, err := r.Uint64(1)
		if err != nil {
			return fmt.Errorf("decode field Field: %w", err)
		}
		f.Field = Index(v)
	}
	return nil
}

// FromRow creates FieldMarshal from given Row.
func (f *FieldMarshal) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field Parent: %w", err)
		}
		f.Parent = Index(v)
	}
	{
		v, err := r.Blob(1)
		if err != nil {
			return fmt.Errorf("decode field NativeType: %w", err)
		}
		f.NativeType = Blob(v)
	}
	return nil
}

// FromRow creates FieldRVA from given Row.
func (f *FieldRVA) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field RVA: %w", err)
		}
		f.RVA = uint32(v)
	}
	{
		v, err := r.Uint64(1)
		if err != nil {
			return fmt.Errorf("decode field Field: %w", err)
		}
		f.Field = Index(v)
	}
	return nil
}

// FromRow creates File from given Row.
func (f *File) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field Flags: %w", err)
		}
		f.Flags = FileAttributes(v)
	}
	{
		v, err := r.String(1)
		if err != nil {
			return fmt.Errorf("decode field Name: %w", err)
		}
		f.Name = string(v)
	}
	{
		v, err := r.Blob(2)
		if err != nil {
			return fmt.Errorf("decode field HashValue: %w", err)
		}
		f.HashValue = Blob(v)
	}
	return nil
}

// FromRow creates GenericParam from given Row.
func (f *GenericParam) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field Number: %w", err)
		}
		f.Number = uint16(v)
	}
	{
		v, err := r.Uint64(1)
		if err != nil {
			return fmt.Errorf("decode field Flags: %w", err)
		}
		f.Flags = GenericParamAttributes(v)
	}
	{
		v, err := r.Uint64(2)
		if err != nil {
			return fmt.Errorf("decode field Owner: %w", err)
		}
		f.Owner = TypeOrMethodDef(v)
	}
	{
		v, err := r.String(3)
		if err != nil {
			return fmt.Errorf("decode field Name: %w", err)
		}
		f.Name = string(v)
	}
	return nil
}

// FromRow creates GenericParamConstraint from given Row.
func (f *GenericParamConstraint) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field Owner: %w", err)
		}
		f.Owner = Index(v)
	}
	{
		v, err := r.Uint64(1)
		if err != nil {
			return fmt.Errorf("decode field Constraint: %w", err)
		}
		f.Constraint = TypeDefOrRef(v)
	}
	return nil
}

// FromRow creates ImplMap from given Row.
func (f *ImplMap) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field MappingFlags: %w", err)
		}
		f.MappingFlags = PInvokeAttributes(v)
	}
	{
		v, err := r.Uint64(1)
		if err != nil {
			return fmt.Errorf("decode field MemberForwarded: %w", err)
		}
		f.MemberForwarded = MemberForwarded(v)
	}
	{
		v, err := r.String(2)
		if err != nil {
			return fmt.Errorf("decode field ImportName: %w", err)
		}
		f.ImportName = string(v)
	}
	{
		v, err := r.Uint64(3)
		if err != nil {
			return fmt.Errorf("decode field ImportScope: %w", err)
		}
		f.ImportScope = Index(v)
	}
	return nil
}

// FromRow creates InterfaceImpl from given Row.
func (f *InterfaceImpl) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field Class: %w", err)
		}
		f.Class = Index(v)
	}
	{
		v, err := r.Uint64(1)
		if err != nil {
			return fmt.Errorf("decode field Interface: %w", err)
		}
		f.Interface = TypeDefOrRef(v)
	}
	return nil
}

// FromRow creates ManifestResource from given Row.
func (f *ManifestResource) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field Offset: %w", err)
		}
		f.Offset = uint32(v)
	}
	{
		v, err := r.Uint64(1)
		if err != nil {
			return fmt.Errorf("decode field Flags: %w", err)
		}
		f.Flags = ManifestResourceAttributes(v)
	}
	{
		v, err := r.String(2)
		if err != nil {
			return fmt.Errorf("decode field Name: %w", err)
		}
		f.Name = string(v)
	}
	{
		v, err := r.Uint64(3)
		if err != nil {
			return fmt.Errorf("decode field Implementation: %w", err)
		}
		f.Implementation = Implementation(v)
	}
	return nil
}

// FromRow creates MemberRef from given Row.
func (f *MemberRef) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field Class: %w", err)
		}
		f.Class = MemberRefParent(v)
	}
	{
		v, err := r.String(1)
		if err != nil {
			return fmt.Errorf("decode field Name: %w", err)
		}
		f.Name = string(v)
	}
	{
		v, err := r.Signature(2)
		if err != nil {
			return fmt.Errorf("decode field Signature: %w", err)
		}
		f.Signature = Signature(v)
	}
	return nil
}

// FromRow creates MethodDef from given Row.
func (f *MethodDef) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field RVA: %w", err)
		}
		f.RVA = uint32(v)
	}
	{
		v, err := r.Uint64(1)
		if err != nil {
			return fmt.Errorf("decode field ImplFlags: %w", err)
		}
		f.ImplFlags = MethodImplAttributes(v)
	}
	{
		v, err := r.Uint64(2)
		if err != nil {
			return fmt.Errorf("decode field Flags: %w", err)
		}
		f.Flags = MethodAttributes(v)
	}
	{
		v, err := r.String(3)
		if err != nil {
			return fmt.Errorf("decode field Name: %w", err)
		}
		f.Name = string(v)
	}
	{
		v, err := r.Signature(4)
		if err != nil {
			return fmt.Errorf("decode field Signature: %w", err)
		}
		f.Signature = Signature(v)
	}
	{
		v, err := r.List(5, md.Param)
		if err != nil {
			return fmt.Errorf("decode field ParamList: %w", err)
		}
		f.ParamList = List(v)
	}
	return nil
}

// FromRow creates MethodImpl from given Row.
func (f *MethodImpl) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field Class: %w", err)
		}
		f.Class = Index(v)
	}
	{
		v, err := r.Uint64(1)
		if err != nil {
			return fmt.Errorf("decode field MethodBody: %w", err)
		}
		f.MethodBody = MethodDefOrRef(v)
	}
	{
		v, err := r.Uint64(2)
		if err != nil {
			return fmt.Errorf("decode field MethodDeclaration: %w", err)
		}
		f.MethodDeclaration = MethodDefOrRef(v)
	}
	return nil
}

// FromRow creates MethodSemantics from given Row.
func (f *MethodSemantics) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field Semantics: %w", err)
		}
		f.Semantics = MethodSemanticsAttributes(v)
	}
	{
		v, err := r.Uint64(1)
		if err != nil {
			return fmt.Errorf("decode field Method: %w", err)
		}
		f.Method = Index(v)
	}
	{
		v, err := r.Uint64(2)
		if err != nil {
			return fmt.Errorf("decode field Association: %w", err)
		}
		f.Association = HasSemantics(v)
	}
	return nil
}

// FromRow creates MethodSpec from given Row.
func (f *MethodSpec) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field Method: %w", err)
		}
		f.Method = MethodDefOrRef(v)
	}
	{
		v, err := r.Blob(1)
		if err != nil {
			return fmt.Errorf("decode field Instantiation: %w", err)
		}
		f.Instantiation = Blob(v)
	}
	return nil
}

// FromRow creates Module from given Row.
func (f *Module) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field Generation: %w", err)
		}
		f.Generation = uint16(v)
	}
	{
		v, err := r.String(1)
		if err != nil {
			return fmt.Errorf("decode field Name: %w", err)
		}
		f.Name = string(v)
	}
	{
		v, err := r.Uint64(2)
		if err != nil {
			return fmt.Errorf("decode field Mvid: %w", err)
		}
		f.Mvid = GUID(v)
	}
	{
		v, err := r.Uint64(3)
		if err != nil {
			return fmt.Errorf("decode field EncId: %w", err)
		}
		f.EncId = GUID(v)
	}
	{
		v, err := r.Uint64(4)
		if err != nil {
			return fmt.Errorf("decode field EncBaseId: %w", err)
		}
		f.EncBaseId = GUID(v)
	}
	return nil
}

// FromRow creates ModuleRef from given Row.
func (f *ModuleRef) FromRow(r Row) error {
	{
		v, err := r.String(0)
		if err != nil {
			return fmt.Errorf("decode field Name: %w", err)
		}
		f.Name = string(v)
	}
	return nil
}

// FromRow creates NestedClass from given Row.
func (f *NestedClass) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field NestedClass: %w", err)
		}
		f.NestedClass = Index(v)
	}
	{
		v, err := r.Uint64(1)
		if err != nil {
			return fmt.Errorf("decode field EnclosingClass: %w", err)
		}
		f.EnclosingClass = Index(v)
	}
	return nil
}

// FromRow creates Param from given Row.
func (f *Param) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field Flags: %w", err)
		}
		f.Flags = FieldAttributes(v)
	}
	{
		v, err := r.Uint64(1)
		if err != nil {
			return fmt.Errorf("decode field Sequence: %w", err)
		}
		f.Sequence = uint16(v)
	}
	{
		v, err := r.String(2)
		if err != nil {
			return fmt.Errorf("decode field Name: %w", err)
		}
		f.Name = string(v)
	}
	return nil
}

// FromRow creates Property from given Row.
func (f *Property) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field Flags: %w", err)
		}
		f.Flags = PropertyAttributes(v)
	}
	{
		v, err := r.String(1)
		if err != nil {
			return fmt.Errorf("decode field Name: %w", err)
		}
		f.Name = string(v)
	}
	{
		v, err := r.Signature(2)
		if err != nil {
			return fmt.Errorf("decode field Type: %w", err)
		}
		f.Type = Signature(v)
	}
	return nil
}

// FromRow creates PropertyMap from given Row.
func (f *PropertyMap) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field Parent: %w", err)
		}
		f.Parent = Index(v)
	}
	{
		v, err := r.List(1, md.Property)
		if err != nil {
			return fmt.Errorf("decode field PropertyList: %w", err)
		}
		f.PropertyList = List(v)
	}
	return nil
}

// FromRow creates TypeDef from given Row.
func (f *TypeDef) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field Flags: %w", err)
		}
		f.Flags = TypeAttributes(v)
	}
	{
		v, err := r.String(1)
		if err != nil {
			return fmt.Errorf("decode field TypeName: %w", err)
		}
		f.TypeName = string(v)
	}
	{
		v, err := r.String(2)
		if err != nil {
			return fmt.Errorf("decode field TypeNamespace: %w", err)
		}
		f.TypeNamespace = string(v)
	}
	{
		v, err := r.Uint64(3)
		if err != nil {
			return fmt.Errorf("decode field Extends: %w", err)
		}
		f.Extends = TypeDefOrRef(v)
	}
	{
		v, err := r.List(4, md.Field)
		if err != nil {
			return fmt.Errorf("decode field FieldList: %w", err)
		}
		f.FieldList = List(v)
	}
	{
		v, err := r.List(5, md.MethodDef)
		if err != nil {
			return fmt.Errorf("decode field MethodList: %w", err)
		}
		f.MethodList = List(v)
	}
	return nil
}

// FromRow creates TypeRef from given Row.
func (f *TypeRef) FromRow(r Row) error {
	{
		v, err := r.Uint64(0)
		if err != nil {
			return fmt.Errorf("decode field ResolutionScope: %w", err)
		}
		f.ResolutionScope = ResolutionScope(v)
	}
	{
		v, err := r.String(1)
		if err != nil {
			return fmt.Errorf("decode field TypeName: %w", err)
		}
		f.TypeName = string(v)
	}
	{
		v, err := r.String(2)
		if err != nil {
			return fmt.Errorf("decode field TypeNamespace: %w", err)
		}
		f.TypeNamespace = string(v)
	}
	return nil
}

// FromRow creates TypeSpec from given Row.
func (f *TypeSpec) FromRow(r Row) error {
	{
		v, err := r.Signature(0)
		if err != nil {
			return fmt.Errorf("decode field Signature: %w", err)
		}
		f.Signature = Signature(v)
	}
	return nil
}
