name: Lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.5

      - name: Install Go
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.16

      - name: Lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: latest
          args: --timeout 5m
          skip-go-installation: true